export enum TypeImage {
    BANNER_EVENT='BANNER_EVENT',
    AVATAR='AVATAR',
    LOGO_EVENT='LOGO_EVENT',
    ARTIST='ARTIST',
    ITEM='ITEM',
    CATEGORY_ITEM='CATEGORY_ITEM',
    MENU_ORDER='MENU_ORDER',
}
